### ISSUE TITLE
bad handshake: Error

### ISSUE THREAD

**Issue by anubhavagar** [Techcatchers/PyLyrics-Extractor#3]
On line:
extract_lyrics = Song_Lyrics(GCS_API_KEY, GCS_ENGINE_ID)

Getting below error:
HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /customsearch/v1/siterestrict?key=XXXXXX&q=summer%20of%2069%20lyrics (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

Can you please advise

**Comment by Techcatchers** [comment]
I tried getting 'summer of 69 lyrics' lyrics from PyLyrics-Extractor and it worked fine. 

Could you please elaborate on your issue with Python version, script and steps to reproduce the above error?

**Comment by anubhavagar** [comment]
Python 3.6
Running code in local on windows machine, using anaconda virtual environment
Issue while searching any song

**Comment by Techcatchers** [comment]
Did you set yourself a custom search engine?

Did you replace  'GCS_API_KEY' and 'GCS_ENGINE_ID' with the API key and Engine ID received while instantiating the class?

Also please try following the [readme](https://github.com/Techcatchers/PyLyrics-Extractor/blob/master/README.md). All the links are available on how to set it up.

**Comment by anubhavagar** [comment]
Yes it is working fine when I run code on kaggle or Google colab notebooks,
issue happen on local machine

**Comment by Techcatchers** [comment]
Check if requests library is updated to the latest version.
Go to line 37 in lyrics.py and add `verify=False` in requests.get method and try again.

:)
